FROM postgres:12.5-alpine
ADD ./postgresql/init-db.sh /docker-entrypoint-initdb.d/
ADD ./postgresql/ctr_dataset.gz /ctr_dataset.gz
ENV POSTGRES_USER=dsp
ENV POSTGRES_PASSWORD=dsppassword
ENV PGDATA=/var/lib/postgresql/data/pgdata