version: "2.2"
services:  
  postgresql:
    build:
      dockerfile: ./postgresql/dockerfile.with_example_data
      context: .
    ports:
      - "5432:5432"
  minio:
    build: 
      dockerfile: ./minio/dockerfile
      context: .
    ports:
      - "9000:9000"
      - "9001:9001"
    environment: 
      - minio_uri=ml-storage:9000
    command: server /data --console-address ":9001"
  redis:
    build:
      dockerfile: ./redis/dockerfile.with_example_data
      context: .
    ports:
      - "6379:6379"
  createbuckets:
    image: minio/mc:RELEASE.2023-07-07T05-25-51Z
    depends_on:
      - minio
    volumes:
      - ./minio/data:/tmp/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add mini-demand-side-platform http://minio:9000 dsp dsppassword;
      /usr/bin/mc rm -r --force mini-demand-side-platform/models;
      /usr/bin/mc mb mini-demand-side-platform/models;
      /usr/bin/mc policy download mini-demand-side-platform/models;
      /usr/bin/mc cp -r /tmp/data/model-default mini-demand-side-platform/models;
      exit 0;
      "
