version: "2.2"
services:  
  postgresql:
    build:
      dockerfile: ./postgresql/dockerfile
      context: .
    ports:
      - "5432:5432"
    networks:
      - mini-demand-side-platform
  minio:
    build: 
      dockerfile: ./minio/dockerfile
      context: .
    ports:
      - "9000:9000"
      - "9001:9001"
    environment: 
      - minio_uri=ml-storage:9000
    command: server /data --console-address ":9001"
    networks:
      - mini-demand-side-platform
  redis:
    build:
      dockerfile: ./redis/dockerfile
      context: .
    ports:
      - "6379:6379"
    networks:
      - mini-demand-side-platform
networks:
  mini-demand-side-platform:
    name: mini-demand-side-platform
    driver: bridge
